### ISSUE TITLE
无法正确导入

### ISSUE THREAD

**Issue by Backl1ght** [zhuxu1/CityPickerX#1]
使用如下命令：
`implementation 'com.utils.cocoz:citypickerx:0.4.2'`
报错：
`Failed to resolve: com.utils.cocoz:citypickerx:0.4.2`

**Comment by zhuxu1** [comment]
老生常谈的问题了，大概率是网络问题引起。
下面是我自己用的配置。或者可参考“https://maven.aliyun.com/mvn/guide” ,添加自行可用的引用

> repositories {
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
        maven { url 'https://jitpack.io' }
        maven { url "https://maven.google.com" }
        mavenLocal()
        google()
        jcenter()
    }

**Comment by Backl1ght** [comment]
应该不是网络问题，我的配置和你差不多，而且我如果用`implementation 'com.utils.cocoz:citypicker:0.3.3`是能正常导入的，但是旧版的EditText会出错

**Comment by Backl1ght** [comment]
emmmmm，直接下载.aar文件然后手动导入就能正常用了

**Comment by zhuxu1** [comment]
我刚才追查了一下，发现了一个报错“Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.”。我也不知道是不是gradle版本导致的，目前已经降低版本然后重新上传了，但是上传效率太慢我的梯子又暂时歇菜了，所以还在尝试。一会上传好我会换台电脑试下然后发布的。

**Comment by zhuxu1** [comment]
已提交0.5.1版本更新，你可以再试试。我自己试support版本有问题，正在排查问题。

**Comment by zhuxu1** [comment]
0.6.0版本已发布，测试AndroidX和support版本均可正常使用。非常感谢你的反馈，由于之前我本地开发各配置版本都是一致的，所以没有发现这种问题。README.md文件与demo下载地址均已经更新，如果你确定此问题已解决或还有其他问题，请及时告知。
如果没有收到你的反馈，本issue将在三日内关闭。
再次感谢你的使用及反馈 @Backl1ght

**Comment by zhuxu1** [comment]
已经新建bintray地址并重新发布到jcenter了，新地址导入错误应该会改观很多。这条issue我先关闭了，如果有问题欢迎继续提交issue
